// Code generated by zenrpc v2.3.0; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	LogService struct{ Get, GetLogsByServiceID, AddTelegramLog string }
}{
	LogService: struct{ Get, GetLogsByServiceID, AddTelegramLog string }{
		Get:                "get",
		GetLogsByServiceID: "getlogsbyserviceid",
		AddTelegramLog:     "addtelegramlog",
	},
}

func (LogService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Get": {
				Parameters: []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]ServiceResponse",
					Items: map[string]string{
						"$ref": "#/definitions/ServiceResponse",
					},
					Definitions: map[string]smd.Definition{
						"ServiceResponse": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "ID",
									Type: smd.String,
								},
								{
									Name: "Name",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
			"GetLogsByServiceID": {
				Parameters: []smd.JSONSchema{
					{
						Name: "serviceID",
						Type: smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "LogsService",
					Properties: smd.PropertyList{
						{
							Name: "service",
							Ref:  "#/definitions/ServiceResponse",
							Type: smd.Object,
						},
						{
							Name: "logs",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/Log",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"ServiceResponse": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "ID",
									Type: smd.String,
								},
								{
									Name: "Name",
									Type: smd.String,
								},
							},
						},
						"Log": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "type",
									Type: smd.String,
								},
								{
									Name: "error_code",
									Type: smd.Integer,
								},
								{
									Name: "message",
									Type: smd.String,
								},
								{
									Name: "tg_user_id",
									Type: smd.Integer,
								},
								{
									Name: "tg_nickname",
									Type: smd.String,
								},
								{
									Name: "service_name",
									Type: smd.String,
								},
								{
									Name: "timestamp",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
			"AddTelegramLog": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "log",
						Type:     smd.Object,
						TypeName: "LogReq",
						Properties: smd.PropertyList{
							{
								Name: "type",
								Type: smd.String,
							},
							{
								Name: "message",
								Type: smd.String,
							},
							{
								Name: "tg_user_id",
								Type: smd.Integer,
							},
							{
								Name: "tg_nickname",
								Type: smd.String,
							},
							{
								Name: "service_name",
								Type: smd.String,
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s LogService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.LogService.Get:
		resp.Set(s.Get(ctx))

	case RPC.LogService.GetLogsByServiceID:
		var args = struct {
			ServiceID int `json:"serviceID"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"serviceID"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetLogsByServiceID(ctx, args.ServiceID))

	case RPC.LogService.AddTelegramLog:
		var args = struct {
			Log LogReq `json:"log"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"log"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.AddTelegramLog(ctx, args.Log))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
