// Code generated by zenrpc v2.3.0; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	LogService struct{ Get string }
}{
	LogService: struct{ Get string }{
		Get: "get",
	},
}

func (LogService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Get": {
				Parameters: []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]ServiceResponse",
					Items: map[string]string{
						"$ref": "#/definitions/ServiceResponse",
					},
					Definitions: map[string]smd.Definition{
						"ServiceResponse": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "ID",
									Type: smd.String,
								},
								{
									Name: "Name",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s LogService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}

	switch method {
	case RPC.LogService.Get:
		resp.Set(s.Get(ctx))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
